#!/bin/bash

export CHUNKC_SOCKET=3920

#
# NOTE: specify the absolutepath to the directory to use when
#       loading a plugin. '~' expansion is supported.
#

chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins
chunkc core::log_file /tmp/chunkwm.err.log

#
# NOTE: if enabled, chunkwm will monitor the specified plugin_dir
#       and automatically reload any '.so' file that is changed.
#

chunkc core::hotload 0

edge=0
edge=40
chunkc set global_desktop_offset_top     $edge
chunkc set global_desktop_offset_bottom  $edge
chunkc set global_desktop_offset_left    $edge
chunkc set global_desktop_offset_right   $edge
chunkc set global_desktop_offset_gap     15

chunkc set global_desktop_mode           bsp
chunkc set bsp_optimal_ratio             1.414213562
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

# chunkc set focused_border_color          0xff0f6288 # blue
# chunkc set focused_border_color          0xffffffc5 # yellow
# chunkc set focused_border_color          0x00000000 # transparent
chunkc set focused_border_width          3
chunkc set focused_border_radius         2
chunkc set focused_border_skip_floating  1
chunkc set focused_border_skip_monocle   1

chunkc set window_float_topmost          0
chunkc set window_fade_inactive          1
chunkc set window_fade_alpha             0.85
chunkc set window_fade_duration          0.25
chunkc set window_use_cgs_move           1

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            all # 'monitor' stays inside one monitor

chunkc set mouse_follows_focus           intrinsic
chunkc set window_float_next             0
chunkc set window_region_locked          1

chunkc set mouse_move_window             \"fn 1\"
chunkc set mouse_resize_window           \"ctrl\"
chunkc set mouse_motion_interval         35

chunkc set preselect_border_color        0xffd75f5f
chunkc set preselect_border_width        5

chunkc set ffm_bypass_modifier fn

# need to load plugins so they can pick up init-only settings

#
# NOTE: specify plugins to load when chunkwm starts.
#

chunkc core::load tiling.so
# chunkc core::load border.so
# chunkc core::load ffm.so

# chunkwm-blur
# chunkc core::load blur.so

#
# NOTE: if chunkc plugin_dir is not set, the absolutepath is necessary.
#

# chunkc load ~/.chunkwm_plugins/tiling.so
# chunkc load ~/.chunkwm_plugins/ffm.so
# chunkc load ~/.chunkwm_plugins/border.so


# Finally the tiling rules, which require a running chunkwm +tiling.so
# reload with :!bash %

chunkc tiling::rule --owner Finder --name Copy --state float
chunkc tiling::rule --owner \"App Store\" --state float
chunkc tiling::rule --owner Things --state float
chunkc tiling::rule --owner Preview --state float
chunkc tiling::rule --owner \"Tor Browser\" --state float
chunkc tiling::rule --owner Zotero --state float
chunkc tiling::rule --owner Reminders --state float
chunkc tiling::rule --owner Firefox --name \"Pinboard - Save a Bookmark$\" --state float --grid-layout 12:12:7:0:5:5
chunkc tiling::rule --owner Skim --state float
chunkc tiling::rule --owner Signal --state float
chunkc tiling::rule --owner Messages --state float
chunkc tiling::rule --owner Messenger --state float
chunkc tiling::rule --owner iTunes --state float


