---
- include_vars: homebrew.yml

- name: Mac App Store
  tags: ['mas']
  import_role:
    name: geerlingguy.mas

- name: Homebrew base
  tags: ['brew']
  import_role:
    name: geerlingguy.homebrew

- name: Install python
  tags: ['brew', 'neovim']
  register: python2
  homebrew:
    name: python
    state: latest

- name: Install python3
  tags: ['brew', 'neovim']
  register: python3
  homebrew:
    name: python
    state: latest

- name: Install neovim
  tags: ['neovim']
  register: neovim
  homebrew:
    name: neovim
    state: latest

- name: Chunkwm
  homebrew:
    name: chunkwm
    state: latest
  register: chunkwm
- shell: brew services restart chunkwm
  when: chunkwm.changed
- name: skhd
  homebrew:
    name: skhd
    state: latest
  register: skhd
- shell: brew services restart skhd
  when: skhd.changed

- name: Install fish
  tags: ['fish']
  homebrew:
    name: fish
    state: present
  register: fish

- name: Copy SFMono font into ~/Library/Fonts
  shell: >
    cd /Applications/Utilities/Terminal.app/Contents/Resources/Fonts/  && cp *.otf ~/Library/Fonts/
