---
- include_vars:
    file: config-debian.yml

- name: Install long list of Apt packages
  apt:
    name: "{{ apt_packages }}"

- name: Fish
  apt:
    name: fish
  register: fish

- name: Neovim
  tags: ['neovim']
  block:
    - name: Python 2 and 3
      apt:
        name: "{{ packages }}"
      register: python
      vars:
        packages:
          - python
          - python-dev
          - python-pip
          - python3
          - python3-dev
          - python3-pip

    - name: Apt repo for neovim
      apt_repository:
        repo: ppa:neovim-ppa/stable

    - name: Install neovim
      apt:
        name: neovim
      register: neovim

- name: ccls git repo
  tags: ['ccls']
  git:
    repo: https://github.com/MaskRay/ccls.git
    dest: "{{ home }}/lib/ccls"
  register: ccls_git

- name:  Install CCLS
  tags: ['ccls']
  block:
    - shell: git submodule update --init
             chdir={{home}}/lib/ccls
    - shell: cmake -H. -BRelease
             chdir={{home}}/lib/ccls
    - shell: cmake --build Release -- -j $(nproc)
             chdir={{home}}/lib/ccls
    - file:
        src: "{{home}}/lib/ccls/Release/ccls"
        dest: "{{dotfiles}}/bin/ccls"
        state: link

