- hosts: all
  vars_files:
    - config.yml
  tasks:
    - name: dotfiles git repo
      tags: ['dotfiles', 'neovim', 'fish', 'tmux']
      when: is_local is not defined
      git:
        repo: https://github.com/cormacrelf/dotfiles.git
        dest: "{{dotfiles}}"
      register: dotfiles_git

    - name: xdg-config directory
      tags: ['dotfiles']
      file:
        path: "{{ home }}/.config"
        state: directory

    - name: home/lib directory
      tags: ['dotfiles']
      file:
        path: "{{ home }}/lib"
        state: directory

    - name: Symlink the dotfiles
      tags: ['dotfiles']
      loop: "{{ symlinks }}"
      file:
        src:  "{{ dotfiles }}/{{ item.src }}"
        dest: "{{ home }}/{{ item.dest }}"
        state: link

    - debug:
        msg: "{{ ansible_distribution }}"

    - when: ansible_distribution == "MacOSX"
      block:
        - import_tasks: macOS/main.yml
        - import_tasks: macOS/rust.yml
        - import_tasks: macOS/alacritty.yml

    - when: ansible_os_family == "Debian"
      block:
        - import_tasks: debian/main.yml

    # expects fish result to be registered
    - import_tasks: tasks/fish.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/nvim-plug.yml

