- hosts: localhost
  vars_files:
    - config.yml
  tasks:
    - name: xdg-config directory
      tags: ['symlink']
      file:
        path: "{{ home }}/.config"
        state: directory

    - name: home/lib directory
      tags: ['symlink']
      file:
        path: "{{ home }}/lib"
        state: directory

    - name: symlink
      tags: ['symlink']
      loop: "{{ symlinks }}"
      file:
        src:  "{{ dotfiles }}/{{ item.src }}"
        dest: "{{ home }}/{{ item.dest }}"
        state: link

    - debug:
        msg: "{{ ansible_distribution }}"

    - when: ansible_distribution == "MacOSX"
      block:
        - import_tasks: macOS/main.yml
        - import_tasks: macOS/rust.yml
        - import_tasks: macOS/alacritty.yml

    - when: ansible_os_family == "Debian"
      block:
        - import_tasks: debian/main.yml

    # expects fish result to be registered
    - import_tasks: fish.yml

    - name: Neovim postinstall
      tags: ['neovim']
      block:
        - name: Neovim > python packages
          pip:
            name: neovim
            executable: "{{item}}"
          loop: ['pip2', 'pip3']
          when: python.changed or neovim.changed

        - name: Neovim > :PlugInstall
          shell: nvim -u {{home}}/.config/nvim/install.vim

